# Выделяем оптимальный объем RAM (4GB) и настраиваем сборщик мусора
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# Оптимизация Kotlin Daemon
kotlin.daemon.jvm.options=-Xmx1536m

# Включаем параллельную сборку модулей
org.gradle.parallel=true

# Включаем кэширование Gradle
org.gradle.caching=true

# Использование AndroidX
android.useAndroidX=true
android.enableJetifier=false

# Путь к кэшу Gradle
gradle.user.home=D:/iqmarket/.gradle_home

# Отключаем инкрементальную компиляцию Kotlin из-за бага Windows (проект на D:, кэш pub на C: вызывает ошибку "different roots")
kotlin.incremental=false
kotlin.incremental.js=false