# Уменьшаем аппетиты Gradle до разумных 2Гб
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
# Оптимизация Kotlin Daemon
kotlin.daemon.jvm.options=-Xmx1024m
# Включаем параллельную сборку
org.gradle.parallel=true
# Включаем кэширование
org.gradle.caching=true
# Использование AndroidX
android.useAndroidX=true
android.enableJetifier=false
# ИСПОЛЬЗУЕМ ВЕРСИЮ 2 ЧТОБЫ ИЗБЕЖАТЬ БИТОГО METADATA.BIN
gradle.user.home=D:/gradle_cache_v2