# Выделяем Gradle 4Гб RAM для супер-быстрой сборки
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC
# Оптимизация Kotlin Daemon
kotlin.daemon.jvm.options=-Xmx1536m
# Включаем параллельную сборку для максимального ускорения
org.gradle.parallel=true
# Включаем кэширование
org.gradle.caching=true
# Использование AndroidX
android.useAndroidX=true
android.enableJetifier=false
# ИСПОЛЬЗУЕМ ВЕРСИЮ 2 ЧТОБЫ ИЗБЕЖАТЬ БИТОГО METADATA.BIN
gradle.user.home=D:/iqmarket/.gradle_home
kotlin.incremental=false
kotlin.incremental.js=false