import 'dart:io';
import 'package:path/path.dart' as path;

void main() async {
  final currentDir = Directory.current.path;
  final rulesDir = Directory(path.join(currentDir, 'firestore_rules'));
  final outputFile = File(path.join(currentDir, 'firestore.rules'));

  print('[BUILD_RULES] Starting Firestore rules compilation...');

  if (!await rulesDir.exists()) {
    print('[BUILD_RULES] Error: "firestore_rules" directory not found at $rulesDir');
    exit(1);
  }

  final files = await rulesDir
      .list()
      .where((entity) => entity is File && entity.path.endsWith('.rules'))
      .cast<File>()
      .toList();

  if (files.isEmpty) {
    print('[BUILD_RULES] Error: No .rules files found in $rulesDir');
    exit(1);
  }

  // Sort files alphabetically so they are concatenated in numerical order
  files.sort((a, b) => path.basename(a.path).compareTo(path.basename(b.path)));

  final buffer = StringBuffer();
  buffer.writeln('// -------------------------------------------------------------');
  buffer.writeln('// AUTO-GENERATED FIRESTORE RULES - DO NOT EDIT THIS FILE DIRECTLY');
  buffer.writeln('// EDIT INDIVIDUAL MODULES IN "firestore_rules/" INSTEAD');
  buffer.writeln('// GENERATED AT: ${DateTime.now().toUtc().toIso8601String()}');
  buffer.writeln('// -------------------------------------------------------------');
  buffer.writeln();

  for (final file in files) {
    final fileName = path.basename(file.path);
    print('[BUILD_RULES] Adding module: $fileName');
    final content = await file.readAsString();

    buffer.writeln('// ==========================================');
    buffer.writeln('// MODULE: $fileName');
    buffer.writeln('// ==========================================');
    buffer.writeln(content);
    buffer.writeln();
  }

  await outputFile.writeAsString(buffer.toString());
  print('[BUILD_RULES] Success! Compiled rules written to ${outputFile.path}');
}
